name: MLOps Pipeline

on:
  push:
    branches: 
      - main
      - 'feature/github-actions-pipeline'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest

      - name: Lint
        run: flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run unit tests
        run: python -m pytest tests/test_train.py -v

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    outputs:
      endpoint_ip: ${{ steps.tf.outputs.endpoint_ip }}
    steps:
      - uses: actions/checkout@v4
      
      # Usar acción oficial de AWS para autenticación segura
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply
        id: tf
        working-directory: ./infra
        run: |
          terraform init
          terraform apply -auto-approve
          echo "endpoint_ip=$(terraform output -raw ec2_instance_public_ip)" >> "$GITHUB_OUTPUT"

  validate:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests pytest python-dotenv

      - name: Run Smoke Test
        env:
          API_HOST: ${{ needs.deploy.outputs.endpoint_ip }}
        run: |
          echo "Esperando a que la API esté lista (max 5 min)..."
          for i in {1..30}; do
            if curl -f http://${{ needs.deploy.outputs.endpoint_ip }}:8000/health; then
              echo "¡Servidor listo!"
              break
            fi
            echo "Aún no listo, reintentando ($i/30)..."
            sleep 10
          done
          
          # Si después del bucle no respondió, fallar el test
          curl -f http://${{ needs.deploy.outputs.endpoint_ip }}:8000/health || exit 1
          
          echo "Corriendo pruebas funcionales..."
          python -m pytest tests/test_endpoint.py -v